- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Animation/Enemy_Animator Controller.controller
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy_Anim.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1025.unity
アクションを起こした際にログを吐きます、あと使用するに当たりアニメーションを弄る必要があります
> 弁慶の攻撃AIの実装・移動及び方向転換

- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Script/Damage_Flash.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Script/Kato_HitBoxE.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Script/Kato_Status_P.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_a.unity
> MutekiDamagetyousei

- Misoten_MainProject/Assets/Demo/Planner/nao/inputaction.inputactions
- Misoten_MainProject/Assets/Demo/Planner/nao/nao_ukenagasicam.unity
- Misoten_MainProject/Assets/Demo/Planner/nao/nao_ukenagasicam.unity.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_HitBoxE_camcheck.cs
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_HitBoxE_camcheck.cs.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_HitBoxP_camcheck.cs
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_HitBoxP_camcheck.cs.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_a_Player_Anim_camcheck.cs
- Misoten_MainProject/Assets/Demo/Planner/nao/script/Kato_a_Player_Anim_camcheck.cs.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/MainCamera.cs
- Misoten_MainProject/Assets/Demo/Planner/nao/script/MainCamera.cs.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/cameramanagerset.cs
- Misoten_MainProject/Assets/Demo/Planner/nao/script/cameramanagerset.cs.meta
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Prefab/sword_test.prefab
- Misoten_MainProject/Assets/Settings/HDRPDefaultResources/DefaultLookDevProfile.asset
- Misoten_MainProject/Assets/Settings/HDRPDefaultResources/DefaultSettingsVolumeProfile.asset
> 受け流し時カメラ作成

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Animation/α/Matsunaga_Enemy01.controller
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy_State.cs
弁慶の縦切りの無限ループ現象の解決
連撃のアニメーション差し替えは別にやります
> アニメーションの再生部分の大規模修正

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Animation/α/Matsunaga_Enemy01.controller
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy_State.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1115.unity
> 連撃のアニメーション差し替え・怯み状態の導入

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Material/matsunaga_Green.mat
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Material/matsunaga_Green.mat.meta
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Model/Char_Enemy01_noRoot.fbx.meta
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Model/mt/M_Benkei01.mat
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Model/mt/M_Benkei02.mat
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Model/mt/M_Benkei03.mat
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Prefab/matsunaga_Baria.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Prefab/matsunaga_Baria.prefab.meta
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Prefab/matsunaga_Denchiku.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Prefab/matsunaga_Denchiku.prefab.meta
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy_State.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1125.unity
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1125.unity.meta
インスペクタービューでサイズの調整ができるようになりました
バリアが内側からも見れるようになりました
> 電竹のサイズ調整機能の実装・バリアのテクスチャの修正

- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Benkei/Mt/Mt_Benkei02.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Benkei/Mt/Mt_Benkei04.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Miburo/Mt/Mt_Player_FaceParts.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Miburo/Mt/Mt_Player_Luminous.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Miburo/Mt/Mt_Player_Weapon.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/Miburo/Mt/Mt_Player_Wear2.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/MoonShader.shadergraph
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/MoonShader.shadergraph.meta
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_Ground.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_KadoHei.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_Kawara.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_Mado.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_Minka.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_Moon.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_NJunoto.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_S1_TadanoBuilding.mat
- Misoten_MainProject/Assets/Demo/Designer/Yoshida/SampleScene/Material/Mt_Tower.mat
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01.meta
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01.unity
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Global Volume Profile 1.asset
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Global Volume Profile 1.asset.meta
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Global Volume Profile.asset
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Global Volume Profile.asset.meta
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Sky and Fog Settings.asset
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Ukenagasi_Scene/Kato_Stage01/Sky and Fog Settings.asset.meta
- Misoten_MainProject/Assets/Settings/SkyandFogSettingsProfile.asset
- Misoten_MainProject/Packages/manifest.json
- Misoten_MainProject/Packages/packages-lock.json
- Misoten_MainProject/ProjectSettings/ProjectSettings.asset
> メインシーンライティング

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Animation/Enemy01_controller.controller
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy_State.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1129_2.unity
スクリプトの再生に関連する部分的な変更がある
アニメーターで、一部変更がある
> アニメーションキャンセルの実装

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
反時計回りはするけど戻った瞬間に次の移動方向の補足が出来ない
> 50%で反時計回り実装

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
インスペクタービューでの調整は効けないため、あとで調整に関しては実装する
> 時間経過での接近を所定位置に到着で接近に変更

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/matsunaga_1205.unity
> 発見された問題の解決(4/5)

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
> "Enemy/matsunaga1205"

- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Script/Miburo_State.cs
> 一旦プレイヤー攻撃時のエフェクト削除

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
> Revert "一旦"

- Misoten_MainProject/Assets/Demo/Planner/nao/Main_Stage01_cam.unity
- Misoten_MainProject/Assets/Demo/Planner/nao/Main_Stage01_cam.unity.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/camera.prefab
- Misoten_MainProject/Assets/Demo/Planner/nao/camera.prefab.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/inputaction.inputactions
- Misoten_MainProject/Assets/Demo/Planner/nao/script/MainCamera.cs
- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/UI/PlayerHUD/AttackIcon/M_UkenagasiIcon.mat
プレイヤーを中心としたロックオンカメラの実装および縦切り時の受け流しカメラの再調整
> カメラ周りの修正＆実装

- Misoten_MainProject/Assets/Demo/Planner/nao/Main_Stage01_cam.unity
- Misoten_MainProject/Assets/Demo/Planner/nao/script/MainCamera.cs
- Misoten_MainProject/Assets/Demo/Programmer/Amano/Effect/Slash_VFX/VFX/vfx_graph_GroundSlash.vfx
- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/UI/PlayerHUD/AttackIcon/M_UkenagasiIcon.mat
> 連撃受け流し時カメラ作成

- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/Scene/ChangeScene.cs
- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/Scene/Title/TitleScene.unity
- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/UI/Option/OptionSet.cs
> Revert "Ui操作Stage,Optionのみ(Test)"

- Misoten_MainProject/Assets/Demo/Planner/nao/Main_Stage01_anime.unity
- Misoten_MainProject/Assets/Demo/Planner/nao/Main_Stage01_anime.unity.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/Miburo_nao.controller
- Misoten_MainProject/Assets/Demo/Planner/nao/Miburo_nao.controller.meta
- Misoten_MainProject/Assets/Demo/Planner/nao/script/MainCamera.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Prefab/Player_Miburo.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Mi-tu-da/UI/PlayerHUD/AttackIcon/M_AttackIcon.mat
> アニメーション速度調整

- Misoten_MainProject/Assets/Demo/Programmer/Amano/Effect/Hit_Slash.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/Drop_Item/script/Billborad.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Prefab/Enemy01.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Script/Enemy01_Box.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy01_State.cs
- Misoten_MainProject/Assets/Prefab/Komono/Drop_Item/Ramen.prefab
- Misoten_MainProject/Assets/Prefab/Komono/Drop_Item/juice.prefab
- Misoten_MainProject/Assets/Scene/Main/Main_Stage01.unity
攻撃成功時と受け流し成功時に、Hit_slashを流す
小物のRigidbodyでY軸の固定
> 攻撃と受け流しのエフェクトの追加と小物の修正

- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/Drop_Item/script/item_drink.cs
- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/Drop_Item/script/item_ramen.cs
- Misoten_MainProject/Assets/Demo/Programmer/Kato/Kato_Prefab/Player_Miburo.prefab
プレイヤーにアイテム限定の当たり判定の追加とアイテムのscript変更
> アイテムの当たり判定の修正

- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/Break_obj/Dropitem_cutmaterial.cs
- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/test_sword.cs
> アイテムの複数生成してたのを修正

- Misoten_MainProject/Assets/Demo/Programmer/Amano/Effect/Heal/vfxgraph_Heal.prefab
- Misoten_MainProject/Assets/Demo/Programmer/Amano/komono/Drop_Item/script/item_ramen.cs
- Misoten_MainProject/Assets/Prefab/Komono/Drop_Item/Ramen.prefab
ラーメンの進行不能バグ、ドリンクが取れないバグ、ラーメン取得時のエフェクトが発生しないバグの修正
> 12月18日17:26時点のバグ修正

- Misoten_MainProject/Assets/Scene/Main/Main_Stage01.unity
> 受け流し用エフェクト色変更

- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_Script/Matsunaga_Enemy02_State.cs
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/Main_Stage02_matsunaga.unity
- Misoten_MainProject/Assets/Demo/Programmer/Matsunaga/Matsunaga_scene/Main_Stage02_matsunaga.unity.meta
> Revert "ベノム・マンティスの処理の実装（アニメーション無し）"

- Misoten_MainProject/Assets/Scene/Main/Main_Stage02.unity
Main_Stage02にヒヤマ大仏を配置しました
光源の色をちょっと調整しました
> Change: Stage02_Lighting
